### ISSUE TITLE
Feature Idea: Adding Support for JSON Messages

### ISSUE THREAD

**Issue by lindig** [lukasmartinelli/pipecat#3]
I’m intrigued by Pipecat for building systems from services. My understanding is that it now works by taking lines as messages like many Unix tools. But I could imagine passing JSON objects as well when connecting programs that take them as input and output. Do you think this makes sense? 

Obviously one could write programs to connect directly to a message broker in the JSON case but I think factoring this out to something like Pipecat during development is a really good idea. The JQ JSON processor could be a also easily incorporated into such an architecture.

It would be possible to pass JSON right now as long as each object is on a single line. However, I would find optional JSON support convincing such that Pipecat would understand the syntax of JSON messages.

**Comment by lukasmartinelli** [comment]
Thanks for the Feedback.

Great idea! Should have thought of that. It could have a `--json` flag that will ensure that only valid JSON messages pass.
Another Golang utility of mine already does that, so I can pretty much copy paste the code https://github.com/lukasmartinelli/pgfutter

It already works now. I actually use it together with JSON.
Had shell script that wrote JSON jobs to a queue (GitHub repos to dwonload) and than a python utility that read the json lines from stdin
and downloaded the GitHub repo and wrote several new JSON messages to stdout which were than backed up again. Last time I used it it scaled well across several million messages - haven't
tested it past that. That scaled quite well. I one time had some issues with very long JSON records (several thousand keys) on one line.

For bigger application I end up baking in message capabilities (but it does not feel very UNIXy).
But I code alot of small utils that I just want to distribute to several hosts that don't do anything fancy
and I also don't want to learn the libraries for each programming language how to connect to RabbitMQ.
It is also more of an idea/showcase how we can simplify distributed messaging again bit it sometimes seems very daunting for other people to get started with message queues even though
it is so similar to UNIX pipes where I really love the concept.

**Comment by lukasmartinelli** [comment]
You think just parsing the line and ensuring it is valid JSON is already useful?
Or what capabilities would be useful?

**Comment by lindig** [comment]
I think in the presence of a `--json` flag the tool should ensure that messages are proper JSON. I think it would be cool if a JSON message could be any JSON data type, not necessarily an object. For example, if the next value is a string, then just the string is processed. The typical use case will be an object, of course, which will be passed in its entirety. If the `ACK` mechanism relies on comparing messages (not sure), some internal normalisation of JSON might be useful such that two messages that differ in the use of whitespace are still considered equal.

**Comment by lukasmartinelli** [comment]
> the ACK mechanism relies on comparing messages

It currently needs to be exactly the same inlcuding trailing whitespaces and everything.

> For example, if the next value is a string, then just the string is processed.
> We actually do not verify the validity of a JSON message but if the `--json` flag is set the
> comparison algorithm differs.

In this case you can actually continue to pass anythong you want into it but it will be compared differently in the ACK input stream (and a tiny bit slower because each line will be parsed) if the `--json` flag is set.

``` javascript
{"name": "Jacob", "age": 26, "friends": ["Anthony"]}
["Jacob", "Anthony"]
Jacob is 26 and friend of Anthony
<xml>My weird XML pseudo record</xml>
```

For each line we try to parse the JSON as Object or Array and if it fails it is not a JSON object but
normal text.

In case of the first two entries the JSON objects would be compared in the Ack algorithm
while in the last two records they are compared as text.

The following would still be valid as ACK stream. (Different field order)

``` javascript
{"age": 26, "friends": ["Anthony"], "name": "Jacob"}
["Jacob", "Anthony"]
```

I don't think it makes sense to store the JSON objects differently than the text messages at the moment. Perhaps I will find a use case once.

**Comment by lindig** [comment]
I think in the presence of `--json` a message like 

```
Jacob is 26 and friend of Anthony
```

should be rejected. According to [json.org](http://json.org), `Jacob` is not a valid JSON value (it would have to be `"Jacob"`).

**Comment by lukasmartinelli** [comment]
Ah I get it know, you mean to support all basic JSON types like JSON array, objects and primitive values.
But not arbitrary text.

``` javascript
{"age": 26, "friends": ["Anthony"], "name": "Jacob"}
["Jacob", "Anthony"]
"Jacob"
1
1.3
true
false
null
```

**Comment by lindig** [comment]
Here is an idea for implementing the `ACK` mechanism that avoids normalisation: you could always deliver a message as an object `{"ack": token, "msg": message}` and expect the receiver to place the _token_ into the file. The _token_ could be a short string, hash, or sequence number.

**Comment by lukasmartinelli** [comment]
> Here is an idea for implementing the ACK mechanism that avoids normalisation: you could always deliver a message as an object {"ack": token, "msg": message} and expect the receiver to place the token into the file. The token could be a short string, hash, or sequence number.

Good idea. If I inject the hash of the message as token in the message delivered to the consumer he can actually just write that hash back into the FACK file handle and I ack that specific message.
1. On the server: `{"msg": message}`
2. Delivered to consumer by pipecat: `{"msg": message, "ack": "<hash>"}`
3. Written to FACK filehandle by consumer: `{"ack": "<hash>"}`

This also doesn't require much client logic. It would still be possible to use a Bash script with jq to extract the `ack` token with this mechanism (If it works in Bash it is polyglot I think :)

First thought about letting the client calculate the hash of the JSON himself but that requires too much logic in the consumer program and is error prone.

Nice how this get's sketched out more and more.

**Comment by lindig** [comment]
I was thinking along this line:
1. On the server: _value_ (any JSON value)
2. Delivered to the consumer by pipecat: `{"msg": <value>, "ack": "<hash>"}`
3. Written to FACK by consumer: `"<hash>"` or even `<hash>`.

**Comment by lukasmartinelli** [comment]
> I was thinking along this line:
> 
> On the server: value (any JSON value)
> Delivered to the consumer by pipecat: {"msg": <value>, "ack": "<hash>"}
> Written to FACK by consumer: "<hash>" or even <hash>.

Exactly. I'll create a prototype based on this spec.

BTW: Just checked out https://webmate.io/ Amazing had a very similar idea - great someone did it. Definitely need to try that out.
